inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - current_session.gemspec

Metrics/BlockLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
